<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>WebAssembly</string>
    <key>scopeName</key>
    <string>source.wasm</string>
    <key>fileTypes</key>
    <array>
      <string>wat</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#string</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
    </array>
    <key>foldingStartMarker</key>
    <string>\(\s*$</string>
    <key>foldingStopMarker</key>
    <string>^\s*\)</string>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>name</key>
        <string>comment.line.semicolon.wasm</string>
        <key>begin</key>
        <string>;;</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.wasm</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
      </dict>
      <key>string</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.wasm</string>
        <key>begin</key>
        <string>(?&lt;!\\)(")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.wasm</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(")</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.wasm</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>constant.character.escape.wasm</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(-?\d+)</string>
            <key>name</key>
            <string>constant.numeric.int.wasm</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(block|if|then|else|end)\b</string>
            <key>name</key>
            <string>keyword.control.conditional.wasm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(loop)\b</string>
            <key>name</key>
            <string>keyword.control.loop.wasm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(import|export)\b</string>
            <key>name</key>
            <string>keyword.control.import.wasm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(unreachable|get_local|set_local|tee_local|get_global|set_global|const)\b</string>
            <key>name</key>
            <string>storage.type.op.wasm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(module|func|param|result)\b</string>
            <key>name</key>
            <string>storage.type.definition.wasm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(i32|i64|f32|f64)\b</string>
            <key>name</key>
            <string>support.type.datatype.wasm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ctz|clz|popcnt)\b</string>
            <key>name</key>
            <string>entity.name.function.unop.wasm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(add|sub|mul)\b</string>
            <key>name</key>
            <string>entity.name.function.binop.wasm</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(eq|ne|lt)\b</string>
            <key>name</key>
            <string>entity.name.function.relop.wasm</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>