<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>WebAssembly</string>
    <key>scopeName</key>
    <string>source.wasm</string>
    <key>fileTypes</key>
    <array>
      <string>wat</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#string</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
    </array>
    <key>foldingStartMarker</key>
    <string>\(\s*$</string>
    <key>foldingStopMarker</key>
    <string>^\s*\)</string>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>name</key>
        <string>comment.line.semicolon.wasm</string>
        <key>begin</key>
        <string>;;</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.wasm</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
      </dict>
      <key>string</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.wasm</string>
        <key>begin</key>
        <string>(?&lt;!\\)(")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.wasm</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(")</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.wasm</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>constant.character.escape.wasm</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(-?\d+)</string>
            <key>name</key>
            <string>constant.numeric.int.wasm</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>